---
- name: Install Common Packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common_packages }}"

- name: Install packages via pip
  pip:
    name: "{{ item }}"
    state: latest
    with_items: "{{ pip_packages }}"  
