---
- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Common Packages
  apt:
    name:
      - "{{ common_packages }}"
      - "{{ debian_packages }}"
    state: latest

- name: Install packages via pip
  pip:
    name:
      - "{{ pip_packages }}"
      - "{{ debian_pip_packages }}"
    state: latest
    executable: pip3

- name: Check for reboot
  shell: if [ -f /var/run/reboot-required ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_hint.stdout.find("reboot") !=1

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: reboot_hint.stdout.find("reboot") !=1
