---
- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Common Packages
  apt:
    name: [ "{{ common_packages }}", "{{ debian_packages }}" ]
    state: latest

- name: Install packages via pip
  pip:
    name: "{{ item }}"
    state: latest
  with_flattened:
    - "{{ pip_packages }}"
    - "{{ debian_pip_packages }}"

- name: Install AWS SSM Agent
  apt:
    name: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
    state: present
  when: is_aws_environment

- name: Ensure SSM agent is started and enabled
  service:
    name: amazon-ssm-agent
    enabled: yes
    state: started
  when: is_aws_environment

- name: Check for reboot
  shell: if [ $(rpm -q kernel|tail -n 1) != kernel-$(uname -r) ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_hint.stdout.find("reboot") !=1

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: reboot_hint.stdout.find("reboot") !=1
