---
- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install Common Packages
  yum:
    name: "{{ common_packages + redhat_packages }}"
    state: latest

- name: Install packages via pip
  pip:
    name: "{{ pip_packages + redhat_pip_packages }}"
    state: latest
    extra_args: "{{ pip_extra_args }}"

- name: Install AWS SSM Agent
  yum:
    name: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
    state: present
  when: is_aws_environment

- name: Ensure SSM agent is started and enabled
  service:
    name: amazon-ssm-agent
    enabled: yes
    state: started
  when: is_aws_environment

- name: Check for reboot
  shell: if [ $(rpm -q kernel|tail -n 1) != kernel-$(uname -r) ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_hint.stdout.find("reboot") !=1

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: reboot_hint.stdout.find("reboot") !=1
